export default {
  btn_back: require('@/assets/record-portarit/btn-back.png'),
  btn_submit_press: require('@/assets/record-portarit/btn-submit-press.png'),
  btn_submit: require('@/assets/record-portarit/btn-submit.png'),
  btn_upload: require('@/assets/record-portarit/btn-upload.png'),
  icon_audio_sprites: require('@/assets/record-portarit/icon-audio-sprites.png'),
  icon_error: require('@/assets/record-portarit/icon-error.png'),
  icon_loading: require('@/assets/record-portarit/icon-loading.png'),
  icon_voice_sprites: require('@/assets/record-portarit/icon-voice-sprites.png'),
  record_again_press: require('@/assets/record-portarit/record-again-press.png'),
  record_again: require('@/assets/record-portarit/record-again.png'),
  record_redo: require('@/assets/record-portarit/record-redo.png'),
  record_new_press: require('@/assets/record-portarit/record-new-press.png'),
  record_new: require('@/assets/record-portarit/record-new.png'),
  record_reopen_press: require('@/assets/record-portarit/record-reopen-press.png'),
  record_reopen: require('@/assets/record-portarit/record-reopen.png'),
  record_stop_press: require('@/assets/record-portarit/record-stop-press.png'),
  record_stop: require('@/assets/record-portarit/record-stop.png'),
  voice_press: require('@/assets/record-portarit/voice-press.png'),
  voice: require('@/assets/record-portarit/voice.png'),
};
